GBC_Travel-Group-54/Controllers/CarController.cs
    using GBC_Travel_Group_54.Data;
    using GBC_Travel_Group_54.Models;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Linq;

    namespace GBC_Travel_Group_54.Controllers
    {
        public class CarController : Controller
        {
            private readonly ApplicationDbContext _context;

            public CarController(ApplicationDbContext context)
            {
                _context = context;
            }

            [HttpGet]
            public IActionResult Index()
            {
                return View();
            }

            [HttpGet]
            public IActionResult Details(int id)
            {
                var car = _context.Cars.FirstOrDefault(c => c.CarId == id);
                if (car == null)
                {
                    return NotFound();
                }
                return View(car);
            }

            [HttpGet]
            public IActionResult Create()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Create([Bind("Make,Model,NumPassenger,Year,RentalCompanies,RentalPricePerDay, NumPassenger")] Car car)
            {
                if (ModelState.IsValid)
                {
                    car.IsAvailable = true; // Assuming the car is available when it's created
                    _context.Cars.Add(car);
                    _context.SaveChanges();
                    return RedirectToAction("ViewAllCars");
                }
                return View(car); // Return the view with validation errors
            }

            [HttpGet]
            public IActionResult Edit(int id)
            {
                var car = _context.Cars.Find(id);
                if (car == null)
                {
                    return NotFound();
                }
                return View(car);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Edit(int id, [Bind("CarId,Make,Model,NumPassenger,Year,RentalCompanies,RentalPricePerDay,IsAvailable")] Car car)
            {
                if (id != car.CarId)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(car);
                        _context.SaveChanges();
                        return RedirectToAction("ViewAllCars");
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CarExists(car.CarId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return RedirectToAction("ViewAllCars");
            }

            private bool CarExists(int carId)
            {
                return _context.Cars.Any(car => car.CarId == carId);
            }

            [HttpGet]
            public IActionResult Delete(int id)
            {
                var car = _context.Cars.FirstOrDefault(c => c.CarId == id);
                if (car == null)
                {
                    return NotFound();

                }
                return View(car);
            }

            [HttpPost, ActionName("DeleteConfirmed")]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteConfirmed(int CarId)
            {
                var car = _context.Cars.Find(CarId);
                if (car != null)
                {
                    _context.Cars.Remove(car);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return NotFound();
            }

            [HttpGet]
            [HttpGet]
            public IActionResult ViewAllCars(string sortOrder, int? passengers, decimal? minPrice, decimal? maxPrice, bool? isAvailable)
            {
                ViewData["PriceSortParm"] = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
                ViewData["YearSortParm"] = sortOrder == "Year" ? "year_desc" : "Year";
                ViewData["PassengerSortParm"] = sortOrder == "Passenger" ? "passenger_desc" : "Passenger";
                ViewData["AvailableSortParm"] = sortOrder == "Available" ? "available_desc" : "Available";

                var cars = from s in _context.Cars select s;

                // Apply filters
                if (passengers.HasValue)
                {
                    cars = cars.Where(c => c.NumPassenger >= passengers);
                }
                if (minPrice.HasValue)
                {
                    cars = cars.Where(c => c.RentalPricePerDay >= minPrice);
                }
                if (maxPrice.HasValue)
                {
                    cars = cars.Where(c => c.RentalPricePerDay <= maxPrice);
                }
                if (isAvailable.HasValue)
                {
                    cars = cars.Where(c => c.IsAvailable == isAvailable);
                }

                // Apply sorting
                switch (sortOrder)
                {
                    case "price_desc":
                        cars = cars.OrderByDescending(s => s.RentalPricePerDay);
                        break;
                    case "Year":
                        cars = cars.OrderBy(s => s.Year);
                        break;
                    case "year_desc":
                        cars = cars.OrderByDescending(s => s.Year);
                        break;
                    case "Passenger":
                        cars = cars.OrderBy(s => s.NumPassenger);
                        break;
                    case "passenger_desc":
                        cars = cars.OrderByDescending(s => s.NumPassenger);
                        break;
                    case "Available":
                        cars = cars.OrderBy(s => s.IsAvailable);
                        break;
                    case "available_desc":
                        cars = cars.OrderByDescending(s => s.IsAvailable);
                        break;
                    default:
                        cars = cars.OrderBy(s => s.RentalPricePerDay);
                        break;
                }

                return View(cars.ToList());
            }


            public IActionResult BookCar(int carId)
            {
                var car = _context.Cars.Find(carId);

                if (car == null)
                {
                    // Handle the case where the car with the specified ID is not found
                    return NotFound();
                }

                // Redirect to the Passenger controller's Create action with car details
                return RedirectToAction("CreateForCar", "Passenger", new { carId = carId });
            }


            [HttpPost]
            public IActionResult SearchCars(int passengers, decimal minPrice, decimal maxPrice)
            {
                // Filter cars based on the number of passengers and price range
                var availableCars = _context.Cars
                    .Where(c => c.NumPassenger >= passengers && c.RentalPricePerDay >= minPrice && c.RentalPricePerDay <= maxPrice)
                    .ToList();

                // Pass the filtered list of available cars to the view
                return View("Index", availableCars);
            }



        }
    }

GBC_Travel-Group-54/Controllers/HotelController.cs
using GBC_Travel_Group_54.Data;
using GBC_Travel_Group_54.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace GBC_Travel_Group_54.Controllers
{
    public class HotelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HotelController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Hotel
        public IActionResult Index(string searchKeyword, int? numGuests, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["LocationSortParm"] = sortOrder == "Location" ? "location_desc" : "Location";
            ViewData["PricingSortParm"] = sortOrder == "Pricing" ? "pricing_desc" : "Pricing";
            ViewData["RatingSortParm"] = sortOrder == "Rating" ? "rating_desc" : "Rating";

            var hotels = from h in _context.Hotels
                         select h;

            if (!String.IsNullOrEmpty(searchKeyword))
            {
                hotels = hotels.Where(h => h.Name.Contains(searchKeyword) || h.Location.Contains(searchKeyword));
            }

            if (numGuests.HasValue)
            {
                hotels = hotels.Where(h => h.NumGuest >= numGuests);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    hotels = hotels.OrderByDescending(h => h.Name);
                    break;
                case "Location":
                    hotels = hotels.OrderBy(h => h.Location);
                    break;
                case "location_desc":
                    hotels = hotels.OrderByDescending(h => h.Location);
                    break;
                case "Pricing":
                    hotels = hotels.OrderBy(h => h.PricingPerNight);
                    break;
                case "pricing_desc":
                    hotels = hotels.OrderByDescending(h => h.PricingPerNight);
                    break;
                case "Rating":
                    hotels = hotels.OrderBy(h => h.Rating);
                    break;
                case "rating_desc":
                    hotels = hotels.OrderByDescending(h => h.Rating);
                    break;
                default:
                    hotels = hotels.OrderBy(h => h.Name);
                    break;
            }

            return View(hotels.ToList());
        }

        [HttpGet]
        // GET: Hotel/ViewAllHotels
        public IActionResult ViewAllHotels(string sortOrder, string searchKeyword, int? numGuests)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["LocationSortParm"] = sortOrder == "Location" ? "location_desc" : "Location";
            ViewData["PricingSortParm"] = sortOrder == "Pricing" ? "pricing_desc" : "Pricing";
            ViewData["RatingSortParm"] = sortOrder == "Rating" ? "rating_desc" : "Rating";

            var hotels = from h in _context.Hotels
                         select h;

            if (!String.IsNullOrEmpty(searchKeyword))
            {
                hotels = hotels.Where(h => h.Location.Contains(searchKeyword));
            }

            if (numGuests.HasValue)
            {
                hotels = hotels.Where(h => h.NumGuest >= numGuests);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    hotels = hotels.OrderByDescending(h => h.Name);
                    break;
                case "Location":
                    hotels = hotels.OrderBy(h => h.Location);
                    break;
                case "location_desc":
                    hotels = hotels.OrderByDescending(h => h.Location);
                    break;
                case "Pricing":
                    hotels = hotels.OrderBy(h => h.PricingPerNight);
                    break;
                case "pricing_desc":
                    hotels = hotels.OrderByDescending(h => h.PricingPerNight);
                    break;
                case "Rating":
                    hotels = hotels.OrderBy(h => h.Rating);
                    break;
                case "rating_desc":
                    hotels = hotels.OrderByDescending(h => h.Rating);
                    break;
                default:
                    hotels = hotels.OrderBy(h => h.Name);
                    break;
            }

            return View(hotels.ToList());
        }



        public IActionResult ViewHotelAmenities(int hotelId)
        {
            var amenities = _context.HotelAmenities
                .Include(ha => ha.Amenity)
                .Where(ha => ha.HotelId == hotelId)
                .Select(ha => ha.Amenity)
                .ToList();

            return View(amenities);
        }


        // GET: Hotel/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = _context.Hotels.FirstOrDefault(m => m.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }
        // GET: Hotel/Create
        public IActionResult Create()
        {
            var predefinedAmenities = _context.Amenities.ToList();
            ViewBag.PredefinedAmenities = new MultiSelectList(predefinedAmenities, "AmenityId", "AmenityName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,NumGuest,Location,PricingPerNight,Rating")] Hotel hotel, List<int> selectedAmenities)
        {
            if (ModelState.IsValid)
            {
                _context.Hotels.Add(hotel);
                _context.SaveChanges();

                if (selectedAmenities != null)
                {
                    foreach (var amenityId in selectedAmenities)
                    {
                        var selectedAmenity = _context.Amenities.Find(amenityId);
                        if (selectedAmenity != null)
                        {
                            _context.HotelAmenities.Add(new HotelAmenities { HotelId = hotel.HotelId, AmenityId = amenityId });
                        }
                    }
                    _context.SaveChanges();
                }

                return RedirectToAction("ViewAllHotels");
            }

            ViewBag.PredefinedAmenities = new MultiSelectList(_context.Amenities.ToList(), "AmenityId", "AmenityName");
            return View(hotel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }


            var predefinedAmenities = _context.Amenities.ToList();
            ViewBag.PredefinedAmenities = new MultiSelectList(predefinedAmenities, "AmenityId", "AmenityName");
            return View(hotel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HotelId,Name,NumGuest,Location,PricingPerNight,Rating")] Hotel hotel, List<int> selectedAmenities)
        {
            if (id != hotel.HotelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hotel);
                    await _context.SaveChangesAsync();

                    // Update amenities
                    var existingAmenities = _context.HotelAmenities.Where(ha => ha.HotelId == hotel.HotelId);
                    _context.HotelAmenities.RemoveRange(existingAmenities);

                    foreach (var amenityId in selectedAmenities)
                    {
                        _context.HotelAmenities.Add(new HotelAmenities { HotelId = hotel.HotelId, AmenityId = amenityId });
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.HotelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ViewAllHotels");
            }
            return RedirectToAction("ViewAllHotels");
        }

        private bool HotelExists(int id)
        {
            return _context.Hotels.Any(e => e.HotelId == id);
        }


        // GET: Hotel/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = _context.Hotels.FirstOrDefault(m => m.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int HotelId)
        {
            var hotel = _context.Hotels.Find(HotelId);
            if (hotel != null)
            {
                _context.Hotels.Remove(hotel);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult SearchHotels(string searchKeyword, int? numGuests, decimal? minPrice, decimal? maxPrice)
        {
            var hotelsQuery = _context.Hotels.AsQueryable();

            if (!string.IsNullOrEmpty(searchKeyword))

GBC_Travel-Group-54/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GBC_Travel_Group_54</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GBC_Travel_Group_54.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GBC_Travel_Group_54</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Shop travel
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" asp-controller="BookingFlight" asp-action="Index">Booking Flights</a>
                        <a class="dropdown-item" asp-controller="BookingCar" asp-action="Index">Booking Cars</a>
                        <a class="dropdown-item" asp-controller="BookingHotel" asp-action="Index">Booking Hotels</a>
                    </div>
                </div>


                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignIn"><i class="fa-solid fa-user-circle"></i>Sign In</a>
                        </li>

                    </ul>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index"><i class="fa-solid fa-folder"></i>Flight</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index"><i class="fa-solid fa-folder"></i>Car</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index"><i class="fa-solid fa-folder"></i>Hotel</a>
                        </li>
                        <li class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Flight" asp-action="ViewAllFlights">View Flights</a>
                                <a class="dropdown-item" asp-controller="Hotel" asp-action="ViewAllHotels">View Hotels</a>
                                <a class="dropdown-item" asp-controller="Car" asp-action="ViewAllCars">View Vehicles</a>
                            </div>

                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><i class="fa-solid fa-user-secret"></i>About</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact"><i class="fa-solid fa-user-circle"></i>Contact us</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-12 text-right">
                    &copy; 2024 - Assignment_Group54 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>